{-# LANGUAGE OverloadedStrings #-}

-- | Spec-conformance tests for xdelta 1.1.x.
--
-- These tests do not go through slap's create or parse paths
-- end-to-end. Each test pins a primitive of the xdelta1 wire
-- format against specific byte sequences, catching the case where
-- slap's encoder and decoder agree on a wrong encoding.
--
-- The EDSIO varint vectors below are sourced from canonical
-- xdelta's @sink_next_uint@ function at
-- @xdelta-1.1.3\/libedsio\/default.c:43-68@. Each expected byte
-- sequence was generated by running that algorithm — copy-pasted
-- into a small C harness — against the corresponding input value.
-- Slap's @putEdsioVarint@ encoder must produce the same bytes as
-- canonical's encoder for the same inputs, or this group fails.
--
-- Today the module covers EDSIO varints. Future tests covering
-- full patch wire layouts (header field positions, control-segment
-- byte layouts, source-record byte order) belong here too.
module Props.XDelta1Conformance (xdelta1ConformanceTests) where

import Props.Helpers (assertFailureT)

import Slap.Binary (putEdsioVarint)
import Slap.ByteParser (runByteParser, edsioVarint)
import Slap.Status (ByteParserError, renderByteParserError)

import Data.ByteString (ByteString)
import qualified Data.ByteString as ByteString
import Data.ByteString.Builder (toLazyByteString)
import qualified Data.ByteString.Lazy as LazyByteString
import Data.Int (Int64)
import Data.Word (Word8, Word64)
import Test.Tasty
import Test.Tasty.HUnit

xdelta1ConformanceTests :: TestTree
xdelta1ConformanceTests = testGroup "XDelta1Conformance"
  [ testGroup "EDSIO varint"
      [ testCase "zero"                          (edsioVarintCase 0          [0x00])
      , testCase "one"                           (edsioVarintCase 1          [0x01])
      , testCase "max-single-byte (127)"         (edsioVarintCase 127        [0x7F])
      , testCase "min-two-byte (128)"            (edsioVarintCase 128        [0x80, 0x01])
      , testCase "255"                           (edsioVarintCase 255        [0xFF, 0x01])
      , testCase "256"                           (edsioVarintCase 256        [0x80, 0x02])
      , testCase "max-two-byte (16383)"          (edsioVarintCase 16383      [0xFF, 0x7F])
      , testCase "min-three-byte (16384)"        (edsioVarintCase 16384      [0x80, 0x80, 0x01])
      , testCase "65536"                         (edsioVarintCase 65536      [0x80, 0x80, 0x04])
      , testCase "max-three-byte (2097151)"      (edsioVarintCase 2097151    [0xFF, 0xFF, 0x7F])
      , testCase "min-four-byte (2097152)"       (edsioVarintCase 2097152    [0x80, 0x80, 0x80, 0x01])
      ]
  ]

----------------------------------------------------------------------------
-- Varint helpers
----------------------------------------------------------------------------

encodeEdsioVarint :: Word64 -> ByteString
encodeEdsioVarint = LazyByteString.toStrict . toLazyByteString . putEdsioVarint

decodeEdsioVarint :: ByteString -> Either ByteParserError Int64
decodeEdsioVarint = runByteParser edsioVarint

-- | Assert that encoding a value produces the expected byte sequence,
-- and that decoding those bytes round-trips back to the original.
edsioVarintCase :: Word64 -> [Word8] -> Assertion
edsioVarintCase value expectedBytes = do
  let encoded  = encodeEdsioVarint value
      expected = ByteString.pack expectedBytes
  assertEqual ("encode " ++ show value) expected encoded
  case decodeEdsioVarint encoded of
    Left parserError ->
      assertFailureT ("decode failed: " <> renderByteParserError parserError)
    Right decoded ->
      assertEqual ("decode " ++ show value) (fromIntegral value) decoded
