{-# LANGUAGE OverloadedStrings #-}

-- | Spec-conformance tests for xdelta 1.1.x.
--
-- These tests do not go through slap's create or parse paths
-- end-to-end. Each test pins a primitive of the xdelta1 wire
-- format against specific byte sequences, catching the case where
-- slap's encoder and decoder agree on a wrong encoding.
--
-- The EDSIO varint vectors below are sourced from canonical
-- xdelta's @sink_next_uint@ function at
-- @xdelta-1.1.3\/libedsio\/default.c:43-68@. Each expected byte
-- sequence was generated by running that algorithm — copy-pasted
-- into a small C harness — against the corresponding input value.
-- Slap's @putEdsioVarint@ encoder must produce the same bytes as
-- canonical's encoder for the same inputs, or this group fails.
--
-- Today the module covers EDSIO varints. Future tests covering
-- full patch wire layouts (header field positions, control-segment
-- byte layouts, source-record byte order) belong here too.
module Props.XDelta1Conformance (xdelta1ConformanceTests) where

import Props.Helpers (assertFailureT)

import Slap.Binary (putEdsioVarint)
import Slap.ByteParser (runByteParser, edsioVarint)
import Slap.Status (ByteParserError(..), renderByteParserError)

import Data.ByteString (ByteString)
import qualified Data.ByteString as ByteString
import Data.ByteString.Builder (toLazyByteString)
import qualified Data.ByteString.Lazy as LazyByteString
import Data.Int (Int64)
import Data.Word (Word8, Word64)
import Test.Tasty
import Test.Tasty.HUnit

xdelta1ConformanceTests :: TestTree
xdelta1ConformanceTests = testGroup "XDelta1Conformance"
  [ testGroup "EDSIO varint"
      [ testCase "zero"                          (edsioVarintCase 0          [0x00])
      , testCase "one"                           (edsioVarintCase 1          [0x01])
      , testCase "max-single-byte (127)"         (edsioVarintCase 127        [0x7F])
      , testCase "min-two-byte (128)"            (edsioVarintCase 128        [0x80, 0x01])
      , testCase "255"                           (edsioVarintCase 255        [0xFF, 0x01])
      , testCase "256"                           (edsioVarintCase 256        [0x80, 0x02])
      , testCase "max-two-byte (16383)"          (edsioVarintCase 16383      [0xFF, 0x7F])
      , testCase "min-three-byte (16384)"        (edsioVarintCase 16384      [0x80, 0x80, 0x01])
      , testCase "65536"                         (edsioVarintCase 65536      [0x80, 0x80, 0x04])
      , testCase "max-three-byte (2097151)"      (edsioVarintCase 2097151    [0xFF, 0xFF, 0x7F])
      , testCase "min-four-byte (2097152)"       (edsioVarintCase 2097152    [0x80, 0x80, 0x80, 0x01])
      -- The xdelta1 wire format stores every integer as a guint32, so
      -- 0xFFFFFFFF is the largest value an EDSIO field can hold — and
      -- it round-trips.
      , testCase "max guint32 (0xFFFFFFFF)"
          (edsioVarintCase 0xFFFFFFFF [0xFF, 0xFF, 0xFF, 0xFF, 0x0F])
      ]
      -- A value past the guint32 ceiling is not a representable
      -- xdelta1 quantity; the decoder refuses it rather than carry a
      -- number the format has no field for (canonical xdelta would
      -- silently truncate it into its guint32). The bytes are
      -- canonical EDSIO output for the over-ceiling value, generated
      -- by the same encoder the cases above pin byte-for-byte.
  , testGroup "EDSIO varint past the guint32 ceiling is refused"
      [ testCase "2^32 (just over)"           (edsioVarintRejected 0x100000000)
      , testCase "2^40"                        (edsioVarintRejected 0x10000000000)
      , testCase "near Int64 max"              (edsioVarintRejected 0x7FFFFFFFFFFFFFFF)
      ]
  ]

----------------------------------------------------------------------------
-- Varint helpers
----------------------------------------------------------------------------

encodeEdsioVarint :: Word64 -> ByteString
encodeEdsioVarint = LazyByteString.toStrict . toLazyByteString . putEdsioVarint

decodeEdsioVarint :: ByteString -> Either ByteParserError Int64
decodeEdsioVarint = runByteParser edsioVarint

-- | Assert that encoding a value produces the expected byte sequence,
-- and that decoding those bytes round-trips back to the original.
edsioVarintCase :: Word64 -> [Word8] -> Assertion
edsioVarintCase value expectedBytes = do
  let encoded  = encodeEdsioVarint value
      expected = ByteString.pack expectedBytes
  assertEqual ("encode " ++ show value) expected encoded
  case decodeEdsioVarint encoded of
    Left parserError ->
      assertFailureT ("decode failed: " <> renderByteParserError parserError)
    Right decoded ->
      assertEqual ("decode " ++ show value) (fromIntegral value) decoded

-- | Assert that decoding the canonical EDSIO encoding of an
-- over-guint32 value is refused with 'ByteParserEdsioVarintExceeds32Bits',
-- naming the value the wire asked for.
edsioVarintRejected :: Word64 -> Assertion
edsioVarintRejected value =
  case decodeEdsioVarint (encodeEdsioVarint value) of
    Left (ByteParserEdsioVarintExceeds32Bits reported) ->
      assertEqual "the refusal names the over-ceiling value"
        (fromIntegral value) reported
    Left other ->
      assertFailureT ("expected the 32-bit-ceiling refusal, got: "
                       <> renderByteParserError other)
    Right decoded ->
      assertFailure ("expected refusal, but decoded " ++ show decoded)
