// The engine's surface, spoken by the engine itself at bake time, so the stage furniture renders before the reactor arrives.
// Generated by bake-engine-surface.mjs (make web-bake-surface).
// Two guards: the census fails when this file and the engine disagree, and the page refuses to boot an engine speaking another surface.
export const engineSurface = {
  "surfaceFormats": [
    {
      "formatCreateTarget": {
        "tag": "CreateDifferential",
        "contents": "CreateBPS"
      },
      "formatToken": "bps",
      "formatDisplayName": "BPS",
      "formatFileExtension": ".bps",
      "formatAcceptedFields": [
        "MetadataEmbeddedBlob"
      ],
      "formatConstraints": [],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [],
      "formatChoiceDefaults": [],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDirect",
        "contents": "CreateIPS"
      },
      "formatToken": "ips",
      "formatDisplayName": "IPS",
      "formatFileExtension": ".ips",
      "formatAcceptedFields": [],
      "formatConstraints": [
        "SMCShapeConstraint"
      ],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [],
      "formatChoiceDefaults": [],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDirect",
        "contents": "CreateIPS32"
      },
      "formatToken": "ips32",
      "formatDisplayName": "IPS32",
      "formatFileExtension": ".ips",
      "formatAcceptedFields": [],
      "formatConstraints": [],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [],
      "formatChoiceDefaults": [],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDirect",
        "contents": "CreateEBP"
      },
      "formatToken": "ebp",
      "formatDisplayName": "EBP",
      "formatFileExtension": ".ebp",
      "formatAcceptedFields": [
        "MetadataTitle",
        "MetadataAuthor",
        "MetadataDescription"
      ],
      "formatConstraints": [],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [],
      "formatChoiceDefaults": [],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDifferential",
        "contents": "CreateUPS"
      },
      "formatToken": "ups",
      "formatDisplayName": "UPS",
      "formatFileExtension": ".ups",
      "formatAcceptedFields": [],
      "formatConstraints": [],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [],
      "formatChoiceDefaults": [],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDirect",
        "contents": "CreatePPF1"
      },
      "formatToken": "ppf1",
      "formatDisplayName": "PPF1",
      "formatFileExtension": ".ppf",
      "formatAcceptedFields": [
        "MetadataDescription"
      ],
      "formatConstraints": [],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [
        [
          "MetadataDescription",
          50
        ]
      ],
      "formatChoiceDefaults": [],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDirect",
        "contents": "CreatePPF2"
      },
      "formatToken": "ppf2",
      "formatDisplayName": "PPF2",
      "formatFileExtension": ".ppf",
      "formatAcceptedFields": [
        "MetadataDescription",
        "MetadataFileIdDiz"
      ],
      "formatConstraints": [],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [
        [
          "MetadataDescription",
          50
        ],
        [
          "MetadataFileIdDiz",
          3072
        ]
      ],
      "formatChoiceDefaults": [],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDirect",
        "contents": "CreatePPF3"
      },
      "formatToken": "ppf3",
      "formatDisplayName": "PPF3",
      "formatFileExtension": ".ppf",
      "formatAcceptedFields": [
        "MetadataDescription",
        "MetadataUndoInclusion",
        "MetadataVerificationInclusion",
        "MetadataImageType",
        "MetadataFileIdDiz"
      ],
      "formatConstraints": [],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [
        [
          "MetadataDescription",
          50
        ],
        [
          "MetadataFileIdDiz",
          3072
        ]
      ],
      "formatChoiceDefaults": [
        [
          "MetadataImageType",
          "bin"
        ]
      ],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDirect",
        "contents": "CreatePPF4"
      },
      "formatToken": "ppf4",
      "formatDisplayName": "PPF4",
      "formatFileExtension": ".ppf",
      "formatAcceptedFields": [],
      "formatConstraints": [],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [],
      "formatChoiceDefaults": [],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDirect",
        "contents": "CreatePMSR"
      },
      "formatToken": "pmsr",
      "formatDisplayName": "PMSR",
      "formatFileExtension": ".pmsr",
      "formatAcceptedFields": [],
      "formatConstraints": [],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [],
      "formatChoiceDefaults": [],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDirect",
        "contents": "CreateNINJA1"
      },
      "formatToken": "ninja1",
      "formatDisplayName": "NINJA1",
      "formatFileExtension": ".rup",
      "formatAcceptedFields": [
        "MetadataRomType"
      ],
      "formatConstraints": [],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [],
      "formatChoiceDefaults": [
        [
          "MetadataRomType",
          "raw"
        ]
      ],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDifferential",
        "contents": "CreateDPS"
      },
      "formatToken": "dps",
      "formatDisplayName": "DPS",
      "formatFileExtension": ".dps",
      "formatAcceptedFields": [
        "MetadataTitle",
        "MetadataAuthor",
        "MetadataVersion",
        "MetadataStability"
      ],
      "formatConstraints": [],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [
        [
          "MetadataTitle",
          64
        ],
        [
          "MetadataAuthor",
          64
        ],
        [
          "MetadataVersion",
          64
        ]
      ],
      "formatChoiceDefaults": [],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDifferential",
        "contents": "CreateNINJA2"
      },
      "formatToken": "ninja2",
      "formatDisplayName": "NINJA2",
      "formatFileExtension": ".rup",
      "formatAcceptedFields": [
        "MetadataTitle",
        "MetadataAuthor",
        "MetadataDescription",
        "MetadataVersion",
        "MetadataRomType",
        "MetadataGenre",
        "MetadataLanguage",
        "MetadataDate",
        "MetadataWebsite",
        "MetadataTextMode"
      ],
      "formatConstraints": [],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [
        [
          "MetadataAuthor",
          84
        ],
        [
          "MetadataVersion",
          11
        ],
        [
          "MetadataTitle",
          256
        ],
        [
          "MetadataGenre",
          48
        ],
        [
          "MetadataLanguage",
          48
        ],
        [
          "MetadataDate",
          8
        ],
        [
          "MetadataWebsite",
          512
        ],
        [
          "MetadataDescription",
          1074
        ]
      ],
      "formatChoiceDefaults": [
        [
          "MetadataRomType",
          "raw"
        ],
        [
          "MetadataTextMode",
          "utf8"
        ]
      ],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDirect",
        "contents": "CreateAPSN64"
      },
      "formatToken": "aps-n64",
      "formatDisplayName": "APS (N64)",
      "formatFileExtension": ".aps",
      "formatAcceptedFields": [
        "MetadataDescription"
      ],
      "formatConstraints": [],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [
        [
          "MetadataDescription",
          50
        ]
      ],
      "formatChoiceDefaults": [],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDifferential",
        "contents": "CreateAPSGBA"
      },
      "formatToken": "aps-gba",
      "formatDisplayName": "APS (GBA)",
      "formatFileExtension": ".aps",
      "formatAcceptedFields": [],
      "formatConstraints": [],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [],
      "formatChoiceDefaults": [],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDifferential",
        "contents": "CreateGDIFF"
      },
      "formatToken": "gdiff",
      "formatDisplayName": "GDIFF",
      "formatFileExtension": ".gdiff",
      "formatAcceptedFields": [],
      "formatConstraints": [],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [],
      "formatChoiceDefaults": [],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDifferential",
        "contents": "CreateBSDiff"
      },
      "formatToken": "bsdiff",
      "formatDisplayName": "BSDiff",
      "formatFileExtension": ".bsdiff",
      "formatAcceptedFields": [],
      "formatConstraints": [],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [],
      "formatChoiceDefaults": [],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDifferential",
        "contents": "CreateXDelta1"
      },
      "formatToken": "xdelta1",
      "formatDisplayName": "XDelta1",
      "formatFileExtension": ".xdelta1",
      "formatAcceptedFields": [
        "MetadataVerificationInclusion",
        "MetadataPatchCompression",
        "MetadataXDelta1FromName",
        "MetadataXDelta1ToName"
      ],
      "formatConstraints": [],
      "formatWindowDefault": null,
      "formatTextFieldCeilings": [],
      "formatChoiceDefaults": [],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDifferential",
        "contents": "CreateRFCVCDIFF"
      },
      "formatToken": "rfc-vcdiff",
      "formatDisplayName": "VCDIFF",
      "formatFileExtension": ".rfc-vcdiff",
      "formatAcceptedFields": [
        "MetadataWindowSize"
      ],
      "formatConstraints": [],
      "formatWindowDefault": {
        "tag": "OneWindowWholeTarget"
      },
      "formatTextFieldCeilings": [],
      "formatChoiceDefaults": [],
      "formatSecondaryChoices": []
    },
    {
      "formatCreateTarget": {
        "tag": "CreateDifferential",
        "contents": "CreateXDelta3"
      },
      "formatToken": "xdelta3",
      "formatDisplayName": "xdelta3",
      "formatFileExtension": ".xdelta3",
      "formatAcceptedFields": [
        "MetadataVerificationInclusion",
        "MetadataPatchCompression",
        "MetadataSecondaryCompressor",
        "MetadataEmbeddedBlob",
        "MetadataWindowSize"
      ],
      "formatConstraints": [],
      "formatWindowDefault": {
        "tag": "WindowsOfBytes",
        "contents": 8388608
      },
      "formatTextFieldCeilings": [],
      "formatChoiceDefaults": [
        [
          "MetadataSecondaryCompressor",
          "lzma"
        ]
      ],
      "formatSecondaryChoices": [
        [
          "lzma",
          "SecondaryLZMA"
        ],
        [
          "djw",
          "SecondaryDJW"
        ],
        [
          "fgk",
          "SecondaryFGK"
        ]
      ]
    }
  ],
  "surfaceMetadataFields": [
    {
      "describedMetadataField": "MetadataTitle",
      "metadataFieldControlKind": {
        "tag": "FreeTextField"
      },
      "metadataFieldFlag": "title"
    },
    {
      "describedMetadataField": "MetadataAuthor",
      "metadataFieldControlKind": {
        "tag": "FreeTextField"
      },
      "metadataFieldFlag": "author"
    },
    {
      "describedMetadataField": "MetadataDescription",
      "metadataFieldControlKind": {
        "tag": "FreeTextField"
      },
      "metadataFieldFlag": "description"
    },
    {
      "describedMetadataField": "MetadataVersion",
      "metadataFieldControlKind": {
        "tag": "FreeTextField"
      },
      "metadataFieldFlag": "patch-version"
    },
    {
      "describedMetadataField": "MetadataUndoInclusion",
      "metadataFieldControlKind": {
        "tag": "ToggleField"
      },
      "metadataFieldFlag": "no-undo"
    },
    {
      "describedMetadataField": "MetadataVerificationInclusion",
      "metadataFieldControlKind": {
        "tag": "ToggleField"
      },
      "metadataFieldFlag": "omit-verification"
    },
    {
      "describedMetadataField": "MetadataPatchCompression",
      "metadataFieldControlKind": {
        "tag": "ToggleField"
      },
      "metadataFieldFlag": "no-compress"
    },
    {
      "describedMetadataField": "MetadataSecondaryCompressor",
      "metadataFieldControlKind": {
        "tag": "ChoiceField",
        "contents": {
          "tag": "SecondaryCompressorChoices",
          "contents": [
            [
              "lzma",
              "SecondaryLZMA"
            ],
            [
              "djw",
              "SecondaryDJW"
            ],
            [
              "fgk",
              "SecondaryFGK"
            ]
          ]
        }
      },
      "metadataFieldFlag": "compress-with"
    },
    {
      "describedMetadataField": "MetadataStability",
      "metadataFieldControlKind": {
        "tag": "ToggleField"
      },
      "metadataFieldFlag": "unstable"
    },
    {
      "describedMetadataField": "MetadataRomType",
      "metadataFieldControlKind": {
        "tag": "ChoiceField",
        "contents": {
          "tag": "RomTypeChoices",
          "contents": [
            [
              "raw",
              "PlatformRaw"
            ],
            [
              "nes",
              "PlatformNES"
            ],
            [
              "fds",
              "PlatformFDS"
            ],
            [
              "snes",
              "PlatformSNES"
            ],
            [
              "n64",
              "PlatformN64"
            ],
            [
              "gb",
              "PlatformGB"
            ],
            [
              "gbc",
              "PlatformGBC"
            ],
            [
              "gba",
              "PlatformGBA"
            ],
            [
              "ngp",
              "PlatformNGP"
            ],
            [
              "ngpc",
              "PlatformNGPC"
            ],
            [
              "sms",
              "PlatformSMS"
            ],
            [
              "gg",
              "PlatformGameGear"
            ],
            [
              "mega",
              "PlatformGenesis"
            ],
            [
              "pce",
              "PlatformPCEngine"
            ],
            [
              "ws",
              "PlatformWonderSwan"
            ],
            [
              "wsc",
              "PlatformWonderSwanColor"
            ],
            [
              "lynx",
              "PlatformLynx"
            ],
            [
              "jag",
              "PlatformJaguar"
            ],
            [
              "gp32",
              "PlatformGP32"
            ]
          ]
        }
      },
      "metadataFieldFlag": "rom-type"
    },
    {
      "describedMetadataField": "MetadataImageType",
      "metadataFieldControlKind": {
        "tag": "ChoiceField",
        "contents": {
          "tag": "ImageTypeChoices",
          "contents": [
            [
              "bin",
              "BIN"
            ],
            [
              "gi",
              "GI"
            ]
          ]
        }
      },
      "metadataFieldFlag": "image-type"
    },
    {
      "describedMetadataField": "MetadataFileIdDiz",
      "metadataFieldControlKind": {
        "tag": "FileField"
      },
      "metadataFieldFlag": "diz"
    },
    {
      "describedMetadataField": "MetadataGenre",
      "metadataFieldControlKind": {
        "tag": "FreeTextField"
      },
      "metadataFieldFlag": "genre"
    },
    {
      "describedMetadataField": "MetadataLanguage",
      "metadataFieldControlKind": {
        "tag": "FreeTextField"
      },
      "metadataFieldFlag": "language"
    },
    {
      "describedMetadataField": "MetadataDate",
      "metadataFieldControlKind": {
        "tag": "FreeTextField"
      },
      "metadataFieldFlag": "date"
    },
    {
      "describedMetadataField": "MetadataWebsite",
      "metadataFieldControlKind": {
        "tag": "FreeTextField"
      },
      "metadataFieldFlag": "website"
    },
    {
      "describedMetadataField": "MetadataTextMode",
      "metadataFieldControlKind": {
        "tag": "ChoiceField",
        "contents": {
          "tag": "TextModeChoices",
          "contents": [
            [
              "utf8",
              "TextModeUTF8"
            ],
            [
              "undeclared",
              "TextModeUndeclared"
            ]
          ]
        }
      },
      "metadataFieldFlag": "ninja2-text-mode"
    },
    {
      "describedMetadataField": "MetadataEmbeddedBlob",
      "metadataFieldControlKind": {
        "tag": "FileField"
      },
      "metadataFieldFlag": "metadata"
    },
    {
      "describedMetadataField": "MetadataXDelta1FromName",
      "metadataFieldControlKind": {
        "tag": "FreeTextField"
      },
      "metadataFieldFlag": "from-name"
    },
    {
      "describedMetadataField": "MetadataXDelta1ToName",
      "metadataFieldControlKind": {
        "tag": "FreeTextField"
      },
      "metadataFieldFlag": "to-name"
    },
    {
      "describedMetadataField": "MetadataWindowSize",
      "metadataFieldControlKind": {
        "tag": "NumberField"
      },
      "metadataFieldFlag": "window-size"
    }
  ],
  "surfaceEncodings": [
    {
      "advertisedFamilyLabel": "Unicode",
      "advertisedFamilyMembers": [
        "utf-8",
        "utf-16",
        "utf-32"
      ]
    },
    {
      "advertisedFamilyLabel": "ISO 8859",
      "advertisedFamilyMembers": [
        "iso-8859-1",
        "iso-8859-2",
        "iso-8859-3",
        "iso-8859-4",
        "iso-8859-5",
        "iso-8859-6",
        "iso-8859-7",
        "iso-8859-8",
        "iso-8859-9",
        "iso-8859-10",
        "iso-8859-11",
        "iso-8859-13",
        "iso-8859-14",
        "iso-8859-15",
        "iso-8859-16"
      ]
    },
    {
      "advertisedFamilyLabel": "Windows",
      "advertisedFamilyMembers": [
        "cp1250",
        "cp1251",
        "cp1252",
        "cp1253",
        "cp1254",
        "cp1255",
        "cp1256",
        "cp1257",
        "cp1258"
      ]
    },
    {
      "advertisedFamilyLabel": "DOS / OEM",
      "advertisedFamilyMembers": [
        "cp437",
        "cp737",
        "cp775",
        "cp850",
        "cp852",
        "cp855",
        "cp857",
        "cp860",
        "cp861",
        "cp862",
        "cp863",
        "cp864",
        "cp865",
        "cp866",
        "cp869",
        "cp874"
      ]
    },
    {
      "advertisedFamilyLabel": "Japanese",
      "advertisedFamilyMembers": [
        "shift-jis",
        "cp932",
        "iso-2022-jp"
      ]
    },
    {
      "advertisedFamilyLabel": "Chinese",
      "advertisedFamilyMembers": [
        "gb18030"
      ]
    },
    {
      "advertisedFamilyLabel": "Cyrillic",
      "advertisedFamilyMembers": [
        "koi8-r",
        "koi8-u"
      ]
    },
    {
      "advertisedFamilyLabel": "Other",
      "advertisedFamilyMembers": [
        "macintosh",
        "ascii"
      ]
    }
  ],
  "surfaceConsoleHeaders": [
    {
      "describedConsoleHeader": "NESHeader",
      "consoleToken": "nes",
      "consoleName": "NES",
      "consoleWidth": 16
    },
    {
      "describedConsoleHeader": "FrontFarEastHeader",
      "consoleToken": "nes-ffe",
      "consoleName": "NES (FFE)",
      "consoleWidth": 512
    },
    {
      "describedConsoleHeader": "FDSHeader",
      "consoleToken": "fds",
      "consoleName": "FDS",
      "consoleWidth": 16
    },
    {
      "describedConsoleHeader": "GameBoyHeader",
      "consoleToken": "gb",
      "consoleName": "Game Boy",
      "consoleWidth": 512
    },
    {
      "describedConsoleHeader": "SNESHeader",
      "consoleToken": "snes",
      "consoleName": "SNES",
      "consoleWidth": 512
    },
    {
      "describedConsoleHeader": "PCEngineHeader",
      "consoleToken": "pce",
      "consoleName": "PC Engine",
      "consoleWidth": 512
    },
    {
      "describedConsoleHeader": "LynxHeader",
      "consoleToken": "lynx",
      "consoleName": "Lynx",
      "consoleWidth": 64
    },
    {
      "describedConsoleHeader": "Atari7800Header",
      "consoleToken": "a78",
      "consoleName": "Atari 7800",
      "consoleWidth": 128
    }
  ]
};
